#!/bin/bash -l
# ============================================================
# Auto-generated by submit_batch.py for Isambard AI Phase 2
# Config : /lus/lfs1aip2/projects/a5l/egunn/projects/MARLLLM/configs/experiments/12_short_dialogue.yaml
# Created: 2026-04-20T09:54:53
# ============================================================
#
# Hardware: GH200 Grace Hopper — 4 × 96 GB HBM3 GPU, ARM Grace CPU (aarch64)
# Docs   : https://docs.isambard.ac.uk

#SBATCH --job-name=short_dialogue
#SBATCH --nodes=1
#SBATCH --gpus=2
#SBATCH --cpus-per-gpu=8
#SBATCH --time=10:00:00
#SBATCH --partition=workq
#SBATCH --output=/lus/lfs1aip2/projects/a5l/egunn/projects/MARLLLM/slurm_logs/short_dialogue_%j.out
#SBATCH --error=/lus/lfs1aip2/projects/a5l/egunn/projects/MARLLLM/slurm_logs/short_dialogue_%j.err

set -euo pipefail

echo "================================================================"
echo "Job started  : $(date)"
echo "Job ID       : $SLURM_JOB_ID"
echo "Job name     : $SLURM_JOB_NAME"
echo "Node         : $(hostname -s)"
echo "GPUs         : $SLURM_GPUS"
echo "CPUs/GPU     : ${SLURM_CPUS_PER_GPU:-N/A}"
echo "Working dir  : /lus/lfs1aip2/projects/a5l/egunn/projects/MARLLLM"
echo "Config file  : /lus/lfs1aip2/projects/a5l/egunn/projects/MARLLLM/configs/experiments/12_short_dialogue.yaml"
echo "================================================================"

# ── SLURM environment ─────────────────────────────────────────────────────────
echo ""
echo "--- SLURM environment ---"
env | grep -E '^SLURM' | sort
echo ""

# ── GPU inventory (GH200 shows as H100 in nvidia-smi) ────────────────────────
if command -v nvidia-smi &>/dev/null; then
    echo "--- nvidia-smi ---"
    nvidia-smi --query-gpu=index,name,memory.total,driver_version,compute_mode \
               --format=csv,noheader
    echo ""
fi

# ── Modules ───────────────────────────────────────────────────────────────────
module purge
module load cuda/12.6
module load brics/nccl

# ── Environment setup ─────────────────────────────────────────────────────────
cd "/lus/lfs1aip2/projects/a5l/egunn/projects/MARLLLM"

# Model cache — keep large HF downloads off $HOME quota.
export HF_HOME="${PROJECTDIR:-$HOME}/hf_cache"
mkdir -p "$HF_HOME"

# HuggingFace token (forwarded from submission environment; required for gated
# models like Llama).  Job will fail here with a clear message if not set.
# To set: export HF_TOKEN="hf_..." before running submit_batch.py.
if [ -z "${HF_TOKEN:-}" ]; then
    echo "[WARN] HF_TOKEN is not set — gated models (e.g. Llama) will fail to download."
else
    export HUGGING_FACE_HUB_TOKEN="$HF_TOKEN"   # legacy alias used by some tools
    echo "[INFO] HF_TOKEN is set (length ${#HF_TOKEN} chars)."
fi

# NCCL tuning for Slingshot 11 / GH200 NVLink topology.
# brics/nccl module sets NCCL_NET_PLUGIN=ofi; these complement it.
export NCCL_DEBUG=WARN
export NCCL_SOCKET_IFNAME=hsn             # use Slingshot high-speed NICs
export FI_CXI_ATS=0                       # disable address translation for CXI
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

# ── Python / venv ─────────────────────────────────────────────────────────────
if [ -f "/lus/lfs1aip2/projects/a5l/egunn/projects/MARLLLM/.venv/bin/activate" ]; then
    source "/lus/lfs1aip2/projects/a5l/egunn/projects/MARLLLM/.venv/bin/activate"
elif command -v uv &>/dev/null; then
    : # uv run handles the venv automatically
else
    echo "[ERROR] No venv found and uv is not on PATH. Aborting." >&2
    exit 1
fi

echo ""
echo "--- Python / package versions ---"
python --version 2>&1 || true
python -c "
import torch, platform
print(f'torch       {torch.__version__}')
print(f'cuda        {torch.version.cuda}')
print(f'gpu count   {torch.cuda.device_count()}')
print(f'arch        {platform.machine()}')
for i in range(torch.cuda.device_count()):
    p = torch.cuda.get_device_properties(i)
    print(f'  gpu{i}     {p.name} | {p.total_memory/1024**3:.1f} GiB')
" 2>&1 || true
python -c "import transformers; print(f'transformers {transformers.__version__}')" 2>&1 || true
echo ""

# ── Run training ──────────────────────────────────────────────────────────────
echo "--- Training command ---"
echo "uv run --no-sync python "/lus/lfs1aip2/projects/a5l/egunn/projects/MARLLLM/train_negotiation.py" --config "/lus/lfs1aip2/projects/a5l/egunn/projects/MARLLLM/configs/experiments/12_short_dialogue.yaml""
echo ""

uv run --no-sync python "/lus/lfs1aip2/projects/a5l/egunn/projects/MARLLLM/train_negotiation.py" --config "/lus/lfs1aip2/projects/a5l/egunn/projects/MARLLLM/configs/experiments/12_short_dialogue.yaml"
EXIT_CODE=$?

echo ""
echo "================================================================"
echo "Job finished : $(date)"
echo "Exit code    : $EXIT_CODE"
echo "================================================================"
exit $EXIT_CODE
